export const LightList = [
  {
    id: 1,
    name: "P-1",
    category: "light",
    subcategory: "classic-lights",
    price: "",
    image: "/light1.jpeg",
    description: "",
  },
  {
    id: 2,
    name: "P-2",
    category: "light",
    subcategory: "classic-lights",
    price: "",
    image: "/light2.jpeg",
    description: "",
  },
  {
    id: 3,
    name: "P-3",
    category: "light",
    subcategory: "classic-lights",
    price: "",
    image: "/light3.jpeg",
    description: "",
  },
  {
    id: 4,
    name: "P-4",
    category: "light",
    subcategory: "classic-lights",
    price: "",
    image: "/light4.jpeg",
    description: "",
  },
  {
    id: 5,
    name: "P-5",
    category: "light",
    subcategory: "classic-lights",
    price: "",
    image: "/light5.jpeg",
    description: "",
  },
  {
    id: 6,
    name: "P-6",
    category: "light",
    subcategory: "classic-lights",
    price: "",
    image: "/light6.jpeg",
    description: "",
  },
  {
    id: 7,
    name: "P-7",
    category: "light",
    subcategory: "classic-lights",
    price: "",
    image: "/light7.jpeg",
    description: "",
  },
  {
    id: 8,
    name: "P-8",
    category: "light",
    subcategory: "classic-lights",
    price: "",
    image: "/light8.jpeg",
    description: "",
  },
  {
    id: 9,
    name: "P-9",
    category: "light",
    subcategory: "classic-lights",
    price: "",
    image: "/light9.jpeg",
    description: "",
  },
  {
    id: 10,
    name: "P-10",
    category: "light",
    subcategory: "classic-lights",
    price: "",
    image: "/light10.jpeg",
    description: "",
  },
  {
    id: 11,
    name: "P-11",
    category: "light",
    subcategory: "classic-lights",
    price: "",
    image: "/light11.jpeg",
    description: "",
  },
  {
    id: 12,
    name: "P-12",
    category: "light",
    subcategory: "classic-lights",
    price: "",
    image: "/light12.jpeg",
    description: "",
  },
  {
    id: 13,
    name: "P-13",
    category: "light",
    subcategory: "classic-lights",
    price: "",
    image: "/light13.jpeg",
    description: "",
  },
  {
    id: 14,
    name: "P-14",
    category: "light",
    subcategory: "classic-lights",
    price: "",
    image: "/light14.jpeg",
    description: "",
  },
  {
    id: 15,
    name: "P-15",
    category: "light",
    subcategory: "classic-lights",
    price: "",
    image: "/light15.jpeg",
    description: "",
  },
  {
    id: 16,
    name: "P-16",
    category: "light",
    subcategory: "classic-lights",
    price: "",
    image: "/light16.jpeg",
    description: "",
  },
  {
    id: 17,
    name: "P-17",
    category: "light",
    subcategory: "classic-lights",
    price: "",
    image: "/light17.jpeg",
    description: "",
  },
  {
    id: 18,
    name: "P-18",
    category: "light",
    subcategory: "classic-lights",
    price: "",
    image: "/light18.jpeg",
    description: "",
  },
  {
    id: 19,
    name: "P-19",
    category: "light",
    subcategory: "classic-lights",
    price: "",
    image: "/light19.jpeg",
    description: "",
  },
  {
    id: 20,
    name: "P-20",
    category: "light",
    subcategory: "classic-lights",
    price: "",
    image: "/light20.jpeg",
    description: "",
  },
  {
    id: 21,
    name: "P-21",
    category: "light",
    subcategory: "classic-lights",
    price: "",
    image: "/light21.jpeg",
    description: "",
  },
  {
    id: 22,
    name: "P-22",
    category: "light",
    subcategory: "classic-lights",
    price: "",
    image: "/light22.jpeg",
    description: "",
  },
  {
    id: 23,
    name: "P-23",
    category: "light",
    subcategory: "classic-lights",
    price: "",
    image: "/light23.jpeg",
    description: "",
  },
  {
    id: 24,
    name: "P-24",
    category: "light",
    subcategory: "classic-lights",
    price: "",
    image: "/light24.jpeg",
    description: "",
  },
  {
    id: 25,
    name: "P-25",
    category: "light",
    subcategory: "classic-lights",
    price: "",
    image: "/light25.jpeg",
    description: "",
  },
  {
    id: 26,
    name: "P-26",
    category: "light",
    subcategory: "classic-lights",
    price: "",
    image: "/light26.jpeg",
    description: "",
  },
  {
    id: 27,
    name: "P-27",
    category: "light",
    subcategory: "classic-lights",
    price: "",
    image: "/light27.jpeg",
    description: "",
  },
  {
    id: 28,
    name: "P-28",
    category: "light",
    subcategory: "classic-lights",
    price: "",
    image: "/light28.jpeg",
    description: "",
  },
  {
    id: 29,
    name: "P-29",
    category: "light",
    subcategory: "classic-lights",
    price: "",
    image: "/light29.jpeg",
    description: "",
  },
  {
    id: 30,
    name: "P-30",
    category: "light",
    subcategory: "classic-lights",
    price: "",
    image: "/light30.jpeg",
    description: "",
  },
  {
    id: 31,
    name: "P-31",
    category: "light",
    subcategory: "classic-lights",
    price: "",
    image: "/light31.jpeg",
    description: "",
  },
  {
    id: 32,
    name: "P-32",
    category: "light",
    subcategory: "classic-lights",
    price: "",
    image: "/light32.jpeg",
    description: "",
  },
  {
    id: 33,
    name: "P-33",
    category: "light",
    subcategory: "classic-lights",
    price: "",
    image: "/light33.jpeg",
    description: "",
  },
  {
    id: 34,
    name: "P-34",
    category: "light",
    subcategory: "classic-lights",
    price: "",
    image: "/light34.jpeg",
    description: "",
  },
  {
    id: 35,
    name: "P-35",
    category: "light",
    subcategory: "classic-lights",
    price: "",
    image: "/light35.jpeg",
    description: "",
  },
  {
    id: 36,
    name: "P-36",
    category: "light",
    subcategory: "classic-lights",
    price: "",
    image: "/light36.jpeg",
    description: "",
  },
  {
    id: 37,
    name: "P-37",
    category: "light",
    subcategory: "classic-lights",
    price: "",
    image: "/light37.jpeg",
    description: "",
  },
  {
    id: 38,
    name: "P-38",
    category: "light",
    subcategory: "classic-lights",
    price: "",
    image: "/light38.jpeg",
    description: "",
  },
  {
    id: 39,
    name: "P-39",
    category: "light",
    subcategory: "classic-lights",
    price: "",
    image: "/light39.jpeg",
    description: "",
  },
  {
    id: 40,
    name: "P-40",
    category: "light",
    subcategory: "classic-lights",
    price: "",
    image: "/light40.jpeg",
    description: "",
  },
  {
    id: 41,
    name: "P-41",
    category: "light",
    subcategory: "classic-lights",
    price: "",
    image: "/light41.jpeg",
    description: "",
  },
  {
    id: 42,
    name: "P-42",
    category: "light",
    subcategory: "classic-lights",
    price: "",
    image: "/light42.jpeg",
    description: "",
  },
  {
    id: 43,
    name: "P-43",
    category: "light",
    subcategory: "classic-lights",
    price: "",
    image: "/light43.jpeg",
    description: "",
  },
  {
    id: 44,
    name: "P-44",
    category: "light",
    subcategory: "classic-lights",
    price: "",
    image: "/light44.jpeg",
    description: "",
  },
  {
    id: 45,
    name: "P-45",
    category: "light",
    subcategory: "classic-lights",
    price: "",
    image: "/light45.jpeg",
    description: "",
  },
  {
    id: 46,
    name: "P-46",
    category: "light",
    subcategory: "classic-lights",
    price: "",
    image: "/light46.jpeg",
    description: "",
  },
  {
    id: 47,
    name: "P-47",
    category: "light",
    subcategory: "indoor-spotlight",
    price: "",
    image: "/indoorspot1.jpeg",
    description: "",
  },
  {
    id: 48,
    name: "P-48",
    category: "light",
    subcategory: "indoor-spotlight",
    price: "",
    image: "/indoorspot2.jpeg",
    description: "",
  },
  {
    id: 49,
    name: "P-49",
    category: "light",
    subcategory: "indoor-spotlight",
    price: "",
    image: "/indoorspot3.jpeg",
    description: "",
  },
  {
    id: 50,
    name: "P-50",
    category: "light",
    subcategory: "indoor-spotlight",
    price: "",
    image: "/indoorspot4.jpeg",
    description: "",
  },
  {
    id: 51,
    name: "P-51",
    category: "light",
    subcategory: "indoor-spotlight",
    price: "",
    image: "/indoorspot5.jpeg",
    description: "",
  },
  {
    id: 52,
    name: "P-52",
    category: "light",
    subcategory: "indoor-spotlight",
    price: "",
    image: "/indoorspot6.jpeg",
    description: "",
  },
  {
    id: 53,
    name: "P-53",
    category: "light",
    subcategory: "indoor-spotlight",
    price: "",
    image: "/indoorspot7.jpeg",
    description: "",
  },
  {
    id: 54,
    name: "P-54",
    category: "light",
    subcategory: "indoor-spotlight",
    price: "",
    image: "/indoorspot8.jpeg",
    description: "",
  },
  {
    id: 55,
    name: "P-55",
    category: "light",
    subcategory: "indoor-spotlight",
    price: "",
    image: "/indoorspot9.jpeg",
    description: "",
  },
  {
    id: 56,
    name: "P-56",
    category: "light",
    subcategory: "indoor-spotlight",
    price: "",
    image: "/indoorspot10.jpeg",
    description: "",
  },
  {
    id: 57,
    name: "P-57",
    category: "light",
    subcategory: "indoor-spotlight",
    price: "",
    image: "/indoorspot11.jpeg",
    description: "",
  },
  {
    id: 58,
    name: "P-58",
    category: "light",
    subcategory: "indoor-spotlight",
    price: "",
    image: "/indoorspot12.jpeg",
    description: "",
  },
  {
    id: 59,
    name: "P-59",
    category: "light",
    subcategory: "indoor-spotlight",
    price: "",
    image: "/indoorspot13.jpeg",
    description: "",
  },
  {
    id: 60,
    name: "P-60",
    category: "light",
    subcategory: "indoor-spotlight",
    price: "",
    image: "/indoorspot14.jpeg",
    description: "",
  },
  {
    id: 61,
    name: "P-61",
    category: "light",
    subcategory: "indoor-spotlight",
    price: "",
    image: "/indoorspot15.jpeg",
    description: "",
  },
  {
    id: 62,
    name: "P-62",
    category: "light",
    subcategory: "indoor-spotlight",
    price: "",
    image: "/indoorspot16.jpeg",
    description: "",
  },
  {
    id: 63,
    name: "P-63",
    category: "light",
    subcategory: "indoor-spotlight",
    price: "",
    image: "/indoorspot17.jpeg",
    description: "",
  },
  {
    id: 64,
    name: "P-64",
    category: "light",
    subcategory: "indoor-spotlight",
    price: "",
    image: "/indoorspot18.jpeg",
    description: "",
  },
  {
    id: 65,
    name: "P-65",
    category: "light",
    subcategory: "indoor-spotlight",
    price: "",
    image: "/indoorspot19.jpeg",
    description: "",
  },
  {
    id: 66,
    name: "P-66",
    category: "light",
    subcategory: "portable-light",
    price: "",
    image: "/portablelamp1.jpeg",
    description: "",
  },
  {
    id: 67,
    name: "P-67",
    category: "light",
    subcategory: "portable-light",
    price: "",
    image: "/portablelamp2.jpeg",
    description: "",
  },
  {
    id: 68,
    name: "P-68",
    category: "light",
    subcategory: "portable-light",
    price: "",
    image: "/portablelamp3.jpeg",
    description: "",
  },
  {
    id: 69,
    name: "P-69",
    category: "light",
    subcategory: "portable-light",
    price: "",
    image: "/portablelamp4.jpeg",
    description: "",
  },
  {
    id: 70,
    name: "P-70",
    category: "light",
    subcategory: "outdoor-light",
    price: "",
    image: "/outdoorlight1.jpeg",
    description: "",
  },
  {
    id: 71,
    name: "P-71",
    category: "light",
    subcategory: "outdoor-light",
    price: "",
    image: "/outdoorlight2.jpeg",
    description: "",
  },
  {
    id: 72,
    name: "P-72",
    category: "light",
    subcategory: "outdoor-light",
    price: "",
    image: "/outdoorlight3.jpeg",
    description: "",
  },
  {
    id: 73,
    name: "P-73",
    category: "light",
    subcategory: "outdoor-light",
    price: "",
    image: "/outdoorlight4.jpeg",
    description: "",
  },
  {
    id: 74,
    name: "P-74",
    category: "light",
    subcategory: "outdoor-light",
    price: "",
    image: "/outdoorlight5.jpeg",
    description: "",
  },
  {
    id: 75,
    name: "P-75",
    category: "light",
    subcategory: "outdoor-light",
    price: "",
    image: "/outdoorlight6.jpeg",
    description: "",
  },
  {
    id: 76,
    name: "P-76",
    category: "light",
    subcategory: "outdoor-light",
    price: "",
    image: "/outdoorlight7.jpeg",
    description: "",
  },
  {
    id: 77,
    name: "P-77",
    category: "light",
    subcategory: "outdoor-light",
    price: "",
    image: "/outdoorlight8.jpeg",
    description: "",
  },
  {
    id: 78,
    name: "P-78",
    category: "light",
    subcategory: "outdoor-light",
    price: "",
    image: "/outdoorlight9.jpeg",
    description: "",
  },
  {
    id: 79,
    name: "P-79",
    category: "light",
    subcategory: "outdoor-light",
    price: "",
    image: "/outdoorlight10.jpeg",
    description: "",
  },
  {
    id: 80,
    name: "P-80",
    category: "light",
    subcategory: "outdoor-light",
    price: "",
    image: "/outdoorlight11.jpeg",
    description: "",
  },
  {
    id: 81,
    name: "P-81",
    category: "light",
    subcategory: "outdoor-light",
    price: "",
    image: "/outdoorlight12.jpeg",
    description: "",
  },
  {
    id: 82,
    name: "P-82",
    category: "light",
    subcategory: "outdoor-light",
    price: "",
    image: "/outdoorlight13.jpeg",
    description: "",
  },
  {
    id: 83,
    name: "P-83",
    category: "light",
    subcategory: "outdoor-light",
    price: "",
    image: "/outdoorlight14.jpeg",
    description: "",
  },
  {
    id: 84,
    name: "P-84",
    category: "light",
    subcategory: "outdoor-light",
    price: "",
    image: "/outdoorlight15.jpeg",
    description: "",
  },
  {
    id: 85,
    name: "P-85",
    category: "light",
    subcategory: "outdoor-light",
    price: "",
    image: "/outdoorlight16.jpeg",
    description: "",
  },
  {
    id: 86,
    name: "P-86",
    category: "light",
    subcategory: "outdoor-light",
    price: "",
    image: "/outdoorlight17.jpeg",
    description: "",
  },
  {
    id: 87,
    name: "P-87",
    category: "light",
    subcategory: "outdoor-light",
    price: "",
    image: "/outdoorlight18.jpeg",
    description: "",
  },
  {
    id: 88,
    name: "P-88",
    category: "light",
    subcategory: "outdoor-light",
    price: "",
    image: "/outdoorlight19.jpeg",
    description: "",
  },
  {
    id: 89,
    name: "P-89",
    category: "light",
    subcategory: "outdoor-light",
    price: "",
    image: "/outdoorlight20.jpeg",
    description: "",
  },
  {
    id: 90,
    name: "P-90",
    category: "light",
    subcategory: "outdoor-light",
    price: "",
    image: "/outdoorlight21.jpeg",
    description: "",
  },
  {
    id: 91,
    name: "P-91",
    category: "light",
    subcategory: "outdoor-light",
    price: "",
    image: "/outdoorlight22.jpeg",
    description: "",
  },
  {
    id: 92,
    name: "P-92",
    category: "light",
    subcategory: "outdoor-light",
    price: "",
    image: "/outdoorlight23.jpeg",
    description: "",
  },
  {
    id: 93,
    name: "P-93",
    category: "light",
    subcategory: "outdoor-light",
    price: "",
    image: "/outdoorlight24.jpeg",
    description: "",
  },
  {
    id: 94,
    name: "P-94",
    category: "light",
    subcategory: "outdoor-light",
    price: "",
    image: "/outdoorlight25.jpeg",
    description: "",
  },
  {
    id: 95,
    name: "P-95",
    category: "light",
    subcategory: "outdoor-light",
    price: "",
    image: "/outdoorlight26.jpeg",
    description: "",
  },
  {
    id: 96,
    name: "P-96",
    category: "light",
    subcategory: "outdoor-light",
    price: "",
    image: "/outdoorlight27.jpeg",
    description: "",
  },
];

export const PoolList = [
  {
    id: 97,
    name: "P-97",
    category: "pool",
    subcategory: "pool-nozzle",
    price: "",
    image: "/poolnozzle1.jpeg",
    description: "",
  },
  {
    id: 98,
    name: "P-98",
    category: "pool",
    subcategory: "pool-nozzle",
    price: "",
    image: "/poolnozzle2.jpeg",
    description: "",
  },
  {
    id: 99,
    name: "P-99",
    category: "pool",
    subcategory: "pool-nozzle",
    price: "",
    image: "/poolnozzle3.jpeg",
    description: "",
  },
  {
    id: 100,
    name: "P-100",
    category: "pool",
    subcategory: "pool-nozzle",
    price: "",
    image: "/poolnozzle4.jpeg",
    description: "",
  },
  {
    id: 101,
    name: "P-101",
    category: "pool",
    subcategory: "pool-nozzle",
    price: "",
    image: "/poolnozzle5.jpeg",
    description: "",
  },
  {
    id: 102,
    name: "P-102",
    category: "pool",
    subcategory: "pool-nozzle",
    price: "",
    image: "/poolnozzle6.jpeg",
    description: "",
  },
  {
    id: 103,
    name: "P-103",
    category: "pool",
    subcategory: "pool-nozzle",
    price: "",
    image: "/poolnozzle7.jpeg",
    description: "",
  },
  {
    id: 104,
    name: "P-104",
    category: "pool",
    subcategory: "pool-nozzle",
    price: "",
    image: "/poolnozzle8.jpeg",
    description: "",
  },
  {
    id: 105,
    name: "P-105",
    category: "pool",
    subcategory: "pool-nozzle",
    price: "",
    image: "/poolnozzle9.jpeg",
    description: "",
  },
  {
    id: 106,
    name: "P-106",
    category: "pool",
    subcategory: "pool-nozzle",
    price: "",
    image: "/poolnozzle10.jpeg",
    description: "",
  },
  {
    id: 107,
    name: "P-107",
    category: "pool",
    subcategory: "pool-nozzle",
    price: "",
    image: "/poolnozzle11.jpeg",
    description: "",
  },
  {
    id: 108,
    name: "P-108",
    category: "pool",
    subcategory: "pool-light",
    price: "",
    image: "/poollight1.jpeg",
    description: "",
  },
  {
    id: 109,
    name: "P-109",
    category: "pool",
    subcategory: "pool-light",
    price: "",
    image: "/poollight2.jpeg",
    description: "",
  },
  {
    id: 110,
    name: "P-110",
    category: "pool",
    subcategory: "pool-light",
    price: "",
    image: "/poollight3.jpeg",
    description: "",
  },
  {
    id: 111,
    name: "P-111",
    category: "pool",
    subcategory: "pool-light",
    price: "",
    image: "/poollight4.jpeg",
    description: "",
  },
  {
    id: 112,
    name: "P-112",
    category: "pool",
    subcategory: "pool-light",
    price: "",
    image: "/poollight5.jpeg",
    description: "",
  },
  {
    id: 113,
    name: "P-113",
    category: "pool",
    subcategory: "pool-light",
    price: "",
    image: "/poollight6.jpeg",
    description: "",
  },
  {
    id: 114,
    name: "P-114",
    category: "pool",
    subcategory: "pool-light",
    price: "",
    image: "/poollight7.jpeg",
    description: "",
  },
  {
    id: 115,
    name: "P-115",
    category: "pool",
    subcategory: "pool-light",
    price: "",
    image: "/poollight8.jpeg",
    description: "",
  },
  {
    id: 116,
    name: "P-116",
    category: "pool",
    subcategory: "pool-light",
    price: "",
    image: "/poollight9.jpeg",
    description: "",
  },
  {
    id: 117,
    name: "P-117",
    category: "pool",
    subcategory: "pool-light",
    price: "",
    image: "/poollight10.jpeg",
    description: "",
  },
  {
    id: 118,
    name: "P-118",
    category: "pool",
    subcategory: "pool-light",
    price: "",
    image: "/poollight11.jpeg",
    description: "",
  },
  {
    id: 119,
    name: "P-119",
    category: "pool",
    subcategory: "pool-light",
    price: "",
    image: "/poollight12.jpeg",
    description: "",
  },
  {
    id: 120,
    name: "P-120",
    category: "pool",
    subcategory: "pool-light",
    price: "",
    image: "/poollight13.jpeg",
    description: "",
  },
  {
    id: 121,
    name: "P-121",
    category: "pool",
    subcategory: "pool-light",
    price: "",
    image: "/poollight14.jpeg",
    description: "",
  },
  {
    id: 122,
    name: "P-122",
    category: "pool",
    subcategory: "pool-light",
    price: "",
    image: "/poollight15.jpeg",
    description: "",
  },
  {
    id: 123,
    name: "P-123",
    category: "pool",
    subcategory: "pool-light",
    price: "",
    image: "/poollight16.jpeg",
    description: "",
  },
  {
    id: 124,
    name: "P-124",
    category: "pool",
    subcategory: "test-kit",
    price: "",
    image: "/testkit1.jpeg",
    description: "",
  },
  {
    id: 125,
    name: "P-125",
    category: "pool",
    subcategory: "test-kit",
    price: "",
    image: "/testkit2.jpeg",
    description: "",
  },
  {
    id: 126,
    name: "P-126",
    category: "pool",
    subcategory: "test-kit",
    price: "",
    image: "/testkit3.jpeg",
    description: "",
  },
  {
    id: 127,
    name: "P-127",
    category: "pool",
    subcategory: "test-kit",
    price: "",
    image: "/testkit4.jpeg",
    description: "",
  },
  {
    id: 128,
    name: "P-128",
    category: "pool",
    subcategory: "pool-ladder",
    price: "",
    image: "/poolladder1.jpeg",
    description: "",
  },
  {
    id: 129,
    name: "P-129",
    category: "pool",
    subcategory: "pool-ladder",
    price: "",
    image: "/poolladder2.jpeg",
    description: "",
  },
  {
    id: 130,
    name: "P-130",
    category: "pool",
    subcategory: "pool-filter",
    price: "",
    image: "/poolfilter1.jpeg",
    description: "",
  },
  {
    id: 131,
    name: "P-131",
    category: "pool",
    subcategory: "pool-filter",
    price: "",
    image: "/poolfilter2.jpeg",
    description: "",
  },
  {
    id: 132,
    name: "P-132",
    category: "pool",
    subcategory: "pool-cleaning-kit",
    price: "",
    image: "/poolcleaningkit1.jpeg",
    description: "",
  },
  {
    id: 133,
    name: "P-133",
    category: "pool",
    subcategory: "pool-cleaning-kit",
    price: "",
    image: "/poolcleaningkit2.jpeg",
    description: "",
  },
  {
    id: 134,
    name: "P-134",
    category: "pool",
    subcategory: "pool-cleaning-kit",
    price: "",
    image: "/poolcleaningkit3.jpeg",
    description: "",
  },
  {
    id: 135,
    name: "P-135",
    category: "pool",
    subcategory: "pool-cleaning-kit",
    price: "",
    image: "/poolcleaningkit4.jpeg",
    description: "",
  },
  {
    id: 136,
    name: "P-136",
    category: "pool",
    subcategory: "pool-cleaning-kit",
    price: "",
    image: "/poolcleaningkit5.jpeg",
    description: "",
  },
  {
    id: 137,
    name: "P-137",
    category: "pool",
    subcategory: "pool-rescue",
    price: "",
    image: "/poolrescue1.jpeg",
    description: "",
  },
  {
    id: 138,
    name: "P-138",
    category: "pool",
    subcategory: "pool-rescue",
    price: "",
    image: "/poolrescue2.jpeg",
    description: "",
  },
  {
    id: 139,
    name: "P-139",
    category: "pool",
    subcategory: "pool-rescue",
    price: "",
    image: "/poolrescue3.jpeg",
    description: "",
  },
];
